In [59]:
import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
import seaborn as sns

#Modeling 

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

In [60]:
credit = pd.read_csv('C:/Users/Sumuk/Desktop/Big Data Certificate/Project V - Python/default of credit card clients v2.csv', index_col="ID")

In [61]:
credit.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
ID                                                                         
1       20000    2          2         1   24      2      2      0      0   
2      120000    2          2         2   26      0      2      0      0   
3       90000    2          2         2   34      0      0      0      0   
4       50000    2          2         1   37      0      0      0      0   
5       50000    1          2         1   57      0      0      0      0   

    PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
ID         ...                                                                  
1       0  ...          0          0          0         0       689         0   
2       0  ...       3272       3455       3261         0      1000      1000   
3       0  ...      14331      14948      15549      1518      1500      1000   
4       0  ...      28314      28959      29547      2000      2019      1200   
5       0  ...      20940      19146      19131      2000     36681     10000   

    PAY_AMT4  PAY_AMT5  PAY_AMT6  def_pay  
ID                                         
1          0         0         0        1  
2       1000         0      2000        1  
3       1000      1000      5000        0  
4       1100      1069      1000        0  
5       9000       689       679        0  

[5 rows x 24 columns]

In [62]:
#Adjusting Data Types
categorical_vars = ['SEX','EDUCATION','MARRIAGE','PAY_1','PAY_2','PAY_3','PAY_4',
                   'PAY_5','PAY_6','def_pay']
credit[categorical_vars] = credit[categorical_vars].astype('category')

credit.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 1 to 30000
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null int64
SEX          30000 non-null category
EDUCATION    30000 non-null category
MARRIAGE     30000 non-null category
AGE          30000 non-null int64
PAY_1        30000 non-null category
PAY_2        30000 non-null category
PAY_3        30000 non-null category
PAY_4        30000 non-null category
PAY_5        30000 non-null category
PAY_6        30000 non-null category
BILL_AMT1    30000 non-null int64
BILL_AMT2    30000 non-null int64
BILL_AMT3    30000 non-null int64
BILL_AMT4    30000 non-null int64
BILL_AMT5    30000 non-null int64
BILL_AMT6    30000 non-null int64
PAY_AMT1     30000 non-null int64
PAY_AMT2     30000 non-null int64
PAY_AMT3     30000 non-null int64
PAY_AMT4     30000 non-null int64
PAY_AMT5     30000 non-null int64
PAY_AMT6     30000 non-null int64
def_pay      30000 non-null category
dtypes: category(10), int64(14)
memory usage:

In [63]:
#Feature Selection
x = credit.iloc[:,0:23]
print('Summary of feature sample')
x.head()

Summary of feature sample


LIMIT_BAL SEX EDUCATION MARRIAGE  AGE PAY_1 PAY_2 PAY_3 PAY_4 PAY_5  ...  \
ID                                                                       ...   
1       20000   2         2        1   24     2     2     0     0     0  ...   
2      120000   2         2        2   26     0     2     0     0     0  ...   
3       90000   2         2        2   34     0     0     0     0     0  ...   
4       50000   2         2        1   37     0     0     0     0     0  ...   
5       50000   1         2        1   57     0     0     0     0     0  ...   

   BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
ID                                                                            
1        689          0          0          0         0       689         0   
2       2682       3272       3455       3261         0      1000      1000   
3      13559      14331      14948      15549      1518      1500      1000   
4      49291      28314      28959      29547      2000      2019      1200   
5      35835      20940      19146      19131      2000     36681     10000   

    PAY_AMT4  PAY_AMT5  PAY_AMT6  
ID                                
1          0         0         0  
2       1000         0      2000  
3       1000      1000      5000  
4       1100      1069      1000  
5       9000       689       679  

[5 rows x 23 columns]

In [64]:
y = credit['def_pay']

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 1)

In [66]:
#Logistic Classification

#Model Parameter Building
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(random_state=1)

#Training model 
logmodel.fit(x_train,y_train)

#Prediction
log_y_pred = logmodel.predict(x_test)

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [67]:
from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score,mean_squared_error, r2_score
from math import sqrt
acc = accuracy_score(y_test, log_y_pred)
roc=roc_auc_score(y_test, log_y_pred)
prec = precision_score(y_test, log_y_pred)
rec = recall_score(y_test, log_y_pred)
f1 = f1_score(y_test, log_y_pred)
rmse = sqrt(mean_squared_error(y_test, log_y_pred))
r_squared = r2_score(y_test, log_y_pred)

log_reg_result = pd.DataFrame([['Logistic Regression', acc, roc, rmse]],
               columns = ['Model', 'Accuracy','ROC', 'RMSE'])
log_reg_result

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


Model  Accuracy  ROC      RMSE
0  Logistic Regression  0.777778  0.5  0.471405

In [68]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(logmodel, x_train, y_train))

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[0.7791744  0.77928571 0.77896842]


In [69]:
#Random Forest Classification

#Model Parameter Building
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100,criterion = 'entropy')

#Training model 
rf.fit(x_train,y_train)

#Prediction
rf_y_pred = rf.predict(x_test)

In [70]:
from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score,mean_squared_error, r2_score
from math import sqrt
acc = accuracy_score(y_test, rf_y_pred)
roc=roc_auc_score(y_test, rf_y_pred)
prec = precision_score(y_test, rf_y_pred)
rec = recall_score(y_test, rf_y_pred)
f1 = f1_score(y_test, rf_y_pred)
rmse = sqrt(mean_squared_error(y_test, rf_y_pred))
r_squared = r2_score(y_test, rf_y_pred)

rf_result = pd.DataFrame([['Random Forest', acc, roc, prec, rec, f1, rmse]],
               columns = ['Model', 'Accuracy','ROC', 'Precision', 'Recall', 'F1 Score', 'RMSE'])
rf_result

Model  Accuracy       ROC  Precision  Recall  F1 Score      RMSE
0  Random Forest  0.814889  0.651357   0.652651   0.357  0.461538  0.430245

In [71]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(rf, x_train, y_train))

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


[0.81016998 0.81528571 0.82397485]


In [72]:
#Stochastic Gradient Descent

#Model Parameter Building
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'log', penalty = 'l1', random_state = 1, learning_rate = 'optimal')

#Training model 
sgd.fit(x_train,y_train)

#Prediction
sgd_y_pred = sgd.predict(x_test)

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [73]:
from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score,mean_squared_error, r2_score
from math import sqrt
acc = accuracy_score(y_test, sgd_y_pred)
roc=roc_auc_score(y_test, sgd_y_pred)
prec = precision_score(y_test, sgd_y_pred)
rec = recall_score(y_test, sgd_y_pred)
f1 = f1_score(y_test, sgd_y_pred)
rmse = sqrt(mean_squared_error(y_test, sgd_y_pred))
r_squared = r2_score(y_test, sgd_y_pred)

sgd_result = pd.DataFrame([['Stochastic Gradient Descent', acc, roc, prec, rec, f1, rmse]],
               columns = ['Model', 'Accuracy','ROC', 'Precision', 'Recall', 'F1 Score', 'RMSE'])
sgd_result

Model  Accuracy       ROC  Precision  Recall  \
0  Stochastic Gradient Descent  0.776889  0.500143       0.25   0.002   

   F1 Score      RMSE  
0  0.003968  0.472346

In [74]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(sgd, x_train, y_train))

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 10

[0.7791744  0.43242857 0.77925418]


C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [75]:
#Decision Trees

#Model Parameter Building
from sklearn.tree import DecisionTreeClassifier
dct = DecisionTreeClassifier(criterion = 'entropy',random_state = 1)

#Training model 
dct.fit(x_train,y_train)

#Prediction
dct_y_pred = dct.predict(x_test)

In [76]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(dct, x_train, y_train))

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


[0.72689616 0.73014286 0.74010573]


In [77]:
#SVM

#Model Parameter Building
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf', random_state = 1)

#Training Model
svm.fit(x_train, y_train)

#Prediction
svm.predict(x_test)

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [78]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(svm, x_train, y_train))

C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Sumuk\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma

[0.77817455 0.77828571 0.77982569]


In [80]:
#Random Forest Optimization & Grid Search

from sklearn.model_selection import GridSearchCV
param_grid_rf = {'n_estimators': [200, 400, 600, 1000],
              'criterion': ['entropy', 'gini'],
              'class_weight' : ['balanced',None]}
grid_search_rf = GridSearchCV(estimator=rf,param_grid=param_grid_rf,scoring='accuracy',cv=5,n_jobs=-1)
grid_search_rf = grid_search_rf.fit(x_train,y_train)

In [81]:
best_accuracy_1 = grid_search_rf.best_score_
print('Accuracy on Cross Validation set :',best_accuracy_1)

Accuracy on Cross Validation set : 0.818


In [82]:
best_parameters_1 = grid_search_rf.best_params_
best_parameters_1

{'class_weight': None, 'criterion': 'gini', 'n_estimators': 400}

In [83]:
rf_y_pred_2 = grid_search_rf.predict(x_test)

In [84]:
from sklearn.metrics import  accuracy_score, f1_score, precision_score, recall_score, roc_auc_score,mean_squared_error, r2_score
from math import sqrt
acc = accuracy_score(y_test, rf_y_pred_2)
roc=roc_auc_score(y_test, rf_y_pred_2)
prec = precision_score(y_test, rf_y_pred_2)
rec = recall_score(y_test, rf_y_pred_2)
f1 = f1_score(y_test, rf_y_pred_2)
rmse = sqrt(mean_squared_error(y_test, rf_y_pred_2))
r_squared = r2_score(y_test, rf_y_pred_2)

rf_result_2 = pd.DataFrame([['Random Forest II', acc, roc, prec, rec, f1, rmse]],
               columns = ['Model', 'Accuracy','ROC', 'Precision', 'Recall', 'F1 Score', 'RMSE'])
rf_result_2

Model  Accuracy       ROC  Precision  Recall  F1 Score      RMSE
0  Random Forest II  0.811889  0.649964   0.636202  0.3585  0.458587  0.433718

In [ ]:
#Summary 

#1)Using a Logistic Regression classifier, we can predict with 78% accuracy, whether a customer is likely to default next month.

#2)Using a Stochastic Gradient Descent classifier, we can predict with 77% accuracy, whether a customer is likely to default next month.

#3)Using a Support Vector Machine classifier, we can predict with 78% accuracy, whether a customer is likely to default next month.

#4)Using a Decision Tree classifier, we can predict with 73% accuracy, whether a customer is likely to default next month.

#5)Using a Random Forest classifier, we can predict with 81% accuracy, whether a customer is likely to default next month.

#The strongest predictors of default are the PAY_X (ie the repayment status in previous months), the LIMIT_BAL & the PAY_AMTX (amount paid in previous months).

#The best performing model was the Random Forest classifier.

#Demographics: We see that females, more educated, singles, and people between 30-40 years old are more likely to make payments on time.